name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.WP_SVN_PASS }}
        SVN_USERNAME: ${{ secrets.WP_SVN_USER }}
        SLUG: talash # optional, remove if GitHub repo name matches SVN slug, including capitalization
